---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: thomn/covr
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
