version: '3'

services:
  covr:
    build: .
    user: "1000"
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      DEBUG: "false"
      SENTRY_DSN: ""
      MONGODB_DSN: "mongodb://mongodb:27017/covr"

  mongodb:
    image: mongo:6
